/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("SpareRequestsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheSpareRequestsList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheSpareRequestsList.onFilterBar().iCheckFilterField("requestNumber");
            Then.onTheSpareRequestsList.onFilterBar().iCheckFilterField("status");
            Then.onTheSpareRequestsList.onFilterBar().iCheckFilterField("priority");
            Then.onTheSpareRequestsList.onFilterBar().iCheckFilterField("technicianName");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheSpareRequestsList.onTable().iCheckColumns(undefined, {"requestNumber":{"header":"Request Number"},"status":{"header":"Status"},"priority":{"header":"Priority"},"technicianName":{"header":"Technician"},"quantity":{"header":"Quantity"},"requestedFor":{"header":"Requested For"},"externalReference":{"header":"External Reference"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheSpareRequestsList.onFilterBar().iExecuteSearch();
            
            Then.onTheSpareRequestsList.onTable().iCheckRows();

            When.onTheSpareRequestsList.onTable().iPressRow(0);
            Then.onTheSpareRequestsObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});