/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("SpareRequestsObjectPageObjectPage journey");

        opaTest("Navigate to SpareRequestsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheSpareRequestsList.onFilterBar().iExecuteSearch();

            Then.onTheSpareRequestsList.onTable().iCheckRows();
            When.onTheSpareRequestsList.onTable().iPressRow(0);

            Then.onTheSpareRequestsObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheSpareRequestsObjectPage.iCheckNumberOfSections(2);
            When.onTheSpareRequestsObjectPage.iPressSectionIconTabFilterButton("FieldGroup::Details");
            Then.onTheSpareRequestsObjectPage.iCheckSection({ section: "FieldGroup::Details" });
            Then.onTheSpareRequestsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "requestNumber" });
            Then.onTheSpareRequestsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "part" });
            Then.onTheSpareRequestsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "quantity" });
            Then.onTheSpareRequestsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "technicianName" });
            Then.onTheSpareRequestsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "technicianEmail" });
            Then.onTheSpareRequestsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "priority" });
            Then.onTheSpareRequestsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "requestedFor" });
            Then.onTheSpareRequestsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "notes" });
            When.onTheSpareRequestsObjectPage.iPressSectionIconTabFilterButton("FieldGroup::Integration");
            Then.onTheSpareRequestsObjectPage.iCheckSection({ section: "FieldGroup::Integration" });
            Then.onTheSpareRequestsObjectPage.onForm({ section: "FieldGroup::Integration" }).iCheckField({ property: "status" });
            Then.onTheSpareRequestsObjectPage.onForm({ section: "FieldGroup::Integration" }).iCheckField({ property: "externalReference" });
            Then.onTheSpareRequestsObjectPage.onForm({ section: "FieldGroup::Integration" }).iCheckField({ property: "lastError" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});